/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 02 19:50:16 GMT 2018
 */

package almoxarifadovirtual.servidor.excecoes;

import org.junit.Test;
import static org.junit.Assert.*;
import almoxarifadovirtual.servidor.excecoes.UsuarioException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UsuarioException_ESTest extends UsuarioException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UsuarioException usuarioException0 = new UsuarioException();
  }
}
